name: Feature Request
description: Request a new feature for this project
title: "[Feat]: "
labels:
  - "feature"
assignees:
  - psypher1
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this feature request!
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature.
      placeholder: "Example: As a [user role], I want to [complete action] so that I can [achieve outcome]"
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: What would you consider to be completion for this feature?
      placeholder: |
        - [ ] [User Role] can [Action] [Resource] 
        - [ ] [User Role] can also [Action] [Resource] 
        - [ ] [Other User Role] cannot [Action] [Resource] 
        ...
    validations:
      required: true
  - type: textarea
    id: scenario
    attributes:
      label: Scenario
      description: Describe a scenario where this feature would be useful.
      placeholder: Under what circumstances would this feature be useful
  - type: textarea
    id: context
    attributes:
      label: Any Additional Context
      description: Any other context or additional information.
      placeholder: Any other context or additional information you wish to share about the proposed feature...
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
